ShareIt первый вариант
GudisaOt/java-shareit pull request #1
Opened 2023-03-12 08:51 UTC by GudisaOt

2023-03-12 10:00 UTC, GudisaOt commented
Я тут наворотил для прохождения проверки, изменения были чисто косметические

2023-03-13 07:25 UTC, andrew-larkin requested changes
Привет! Очень хорошо, остается внести пару правок и мы будем готовы двигаться дальше.

2023-03-13 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/exceptions/NonUniqueException.java
> +public class NonUniqueException extends Exception {
RuntimeException - лучше наследоваться от нее

2023-03-13 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
для этого приложения предлагаю в этом спринте добавить библиотеку mapStruct - она позволяет писать мапперы в одну строчку, а еще она повсеместно используется на реальных проектах, поэтому это будет очень полезно

2023-03-13 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    HashMap<Integer, Item> items = new HashMap<>();
модификатор доступа

2023-03-13 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        this.itemService = itemService;
чтобы не создавать конструктор в контроллере, можно над классом поставить @RequiredArgsConstructor

2023-03-13 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Collection<ItemDto> getAll(@RequestHeader(header) int userId) {
в этом спринте также предлагаю для методов контроллеров добавить класс-обертку ResponseEntity, который возвращает не только json, но и http-статус. Будет выглядеть как-то так: return ResponseEntity.ok().body(itemService.getAll(userId));

2023-03-13 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getById(@PathVariable int id) {
в аргументах методов контроллера лучше не использовать примитивы, а использовать врапперы (int -> Integer), чтобы если нам придет null, мы смогли его обработать

2023-03-13 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserService userService;
аналогичные правки как и в ItemController

2023-03-20 15:02 UTC, GudisaOt commented
Внес правки по всем пунктам. Снова тут тесты постмана не проходят, локально все тесты пройдены

2023-03-20 17:02 UTC, merged