Sprint 14 add-bookings
GudisaOt/java-shareit pull request #2
Opened 2023-04-07 12:12 UTC by GudisaOt

2023-04-07 15:43 UTC, GudisaOt commented
Андрей, добрый день! Гит ругается на файл чекстайл, а я его даже не трогал, постман тесты 
проходит приложение.
![image](https://user-images.githubusercontent.com/104755212/230637444-f64d9cef-07d1-476c-8ce0-ebfffdfea7d7.png)

2023-04-07 22:05 UTC, andrew-larkin requested changes
Добрый день! Хорошая реализация, немного подкорректировать местами и можно двигаться дальше. По поводу ошибок в check-repo - судя по логу жалуется оно на то, что в ПР были добавлены бинарные файлы по типу .jar, .class, DS_Store - если от них избавиться, то все должно пройти как следует.

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapperForItem.java
> +    public static BookingTimesDto toBookingForItem(Booking booking) {
вот это нам уже не нужно, т.к. используется mapStruct

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/MapperForBookingTimes.java
> +public class MapperForBookingTimes {
тоже удалить

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +
@Repository над всеми репозиториями

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional
над запросами, которые возвращают информацию без изменения данных в БД. аннотацию @Transactional стоит указывать с пометкой read-only

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>   * TODO Sprint add-bookings.
todo в реализованных классах можно удалять

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public Map<String, String> unsupportedStatus(BadRequestException e) {
хэндлер стоит вынести из контроллера в отдельный класс

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/CommentMapper.java
> +public class CommentMapper {
поменять на mapStruct

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public void delete(@PathVariable Integer id) {
если метод ничего не возвращает, мы также можем использовать ResponseEntity - указав специальный класс Void внутри

2023-04-07 22:05 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
закомментированный код удаляем

2023-04-08 10:05 UTC, GudisaOt commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
Куратор сказал этот код не удалять, а просто закомментировать, он идет еще из начальной версии с форка

2023-04-08 10:06 UTC, GudisaOt commented
Внес все правки, кроме удаления кода из проперти, выше описал почему.

2023-04-10 08:52 UTC, merged